name: On Base Merge

on:
  push:
    branches: [master] # base branch

jobs:
  on-base-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          # `repo` scope TOKEN
          token: ${{ secrets.PERSONAL_ACTIONS_TOKEN }}
          event-type: update-branches
